### ISSUE TITLE
sample-script/p_parameters/parameters_program.R

### ISSUE THREAD

**Issue by vjolahoxhaj** [IMI-ConcePTION/sample-script#2]
In folder p_parameters/parameters_program I would suggest to change from 3 to the 2 column (data_source_name which is the 3 column is not mandatory and will not always be complete, which can lead to errors)

thisdatasource <- as.character(CDM_SOURCE[1,3])

**Comment by RosaMGini** [comment]
Thank for your suggestion! This is not generalisable, since some DAPs may have access to two different data sources, but we will use your comment to include into the new version of the CDM the requirement that this field is always non-missing, and that it contains a string without spaces (because this is what we use in the program).

Thank you again!!!
